<?php

/**
 * \DrupalSecurity\Sniffs\Credentials\HardcodedCredentialsSniff.
 *
 * @category PHP
 * @package PHP_CodeSniffer
 * @link http://pear.php.net/package/PHP_CodeSniffer
 */
namespace DrupalSecurity\Sniffs\Credentials;

use PHP_CodeSniffer\Files\File;
use PHP_CodeSniffer\Sniffs\Sniff;
use PHP_CodeSniffer\Util\Tokens;
use Symfony\Component\Yaml\Yaml;
use Symfony\Component\Yaml\Exception\ParseException;

/**
 * Detects hardcoded credentials in PHP code and YAML config files.
 *
 * Scans for sensitive keys such as passwords, API keys, tokens, and secrets
 * that contain hardcoded string values. Credentials should be managed via
 * environment variables or the Drupal Key module.
 *
 * @category Credentials
 * @package PHP_CodeSniffer
 * @link https://www.drupal.org/project/key
 */
class HardcodedCredentialsSniff implements Sniff {

  /**
   * Regex pattern matching credential-related key/variable names.
   *
   * @var string
   */
  protected $credentialPattern = '/^(password|passwd|pwd|secret|secret_key|client_secret|consumer_secret|oauth_secret|api_key|apikey|api_secret|api_token|access_token|auth_token|bearer_token|private_key|encryption_key|smtp_password|mail_password|smtp_pass|aws_secret_access_key|aws_access_key_id|azure_key|azure_secret|key_value)$/i';

  /**
   * Placeholder values that should not trigger errors.
   *
   * @var array
   */
  protected $placeholders = [
    '',
    'changeme',
    'xxx',
    'todo',
    'null',
    'none',
    'example',
    'password',
    'your_password_here',
    'your_api_key_here',
    'your_secret_here',
    'insert_here',
  ];

  /**
   * Returns an array of tokens this test wants to listen for.
   *
   * @return array<int|string>
   *   The list of token types to listen for.
   */
  public function register() {
    return [
      T_INLINE_HTML,
      T_VARIABLE,
      T_CONSTANT_ENCAPSED_STRING,
    ];
  }

  /**
   * Processes this test, when one of its tokens is encountered.
   *
   * @param \PHP_CodeSniffer\Files\File $phpcsFile
   *   The current file being processed.
   * @param int $stackPtr
   *   The position of the current token in the stack passed in $tokens.
   *
   * @return void|int
   *   Returns void or the position after the last token to skip processing.
   */
  public function process(File $phpcsFile, $stackPtr) {
    $filename = $phpcsFile->getFilename();
    $extension = strtolower(pathinfo($filename, PATHINFO_EXTENSION));

    if ($extension === 'yml' || $extension === 'yaml') {
      return $this->processYaml($phpcsFile, $stackPtr);
    }

    $tokens = $phpcsFile->getTokens();
    $tokenCode = $tokens[$stackPtr]['code'];

    // T_INLINE_HTML is only relevant for YAML files; skip it for PHP files
    // to avoid unnecessary overhead on every inline HTML token.
    if ($tokenCode === T_INLINE_HTML) {
      return;
    }

    if ($tokenCode === T_VARIABLE) {
      $this->processPhpVariable($phpcsFile, $stackPtr);
    }
    elseif ($tokenCode === T_CONSTANT_ENCAPSED_STRING) {
      $this->processPhpArrayKey($phpcsFile, $stackPtr);
    }
  }

  /**
   * Process YAML files for hardcoded credentials.
   *
   * @param \PHP_CodeSniffer\Files\File $phpcsFile
   *   The current file being processed.
   * @param int $stackPtr
   *   The position of the current token.
   *
   * @return int
   *   Returns the position after the last token to skip re-processing.
   */
  protected function processYaml(File $phpcsFile, $stackPtr) {
    // Use the PHPCS API instead of file_get_contents() — the file contents
    // are already cached in memory, and this also works with stdin input.
    $contents = $phpcsFile->getContent();

    // Respect file-level suppression: # phpcs:ignoreFile anywhere in the file.
    // This is the recommended way to exclude autogenerated YAML files that
    // cannot be fixed. For path-based exclusion of many files, use
    // <exclude-pattern> in a local phpcs.xml instead.
    if (strpos($contents, 'phpcs:ignoreFile') !== FALSE) {
      return ($phpcsFile->numTokens + 1);
    }

    try {
      $info = Yaml::parse($contents);
    }
    catch (ParseException $e) {
      return ($phpcsFile->numTokens + 1);
    }

    if (!is_array($info)) {
      return ($phpcsFile->numTokens + 1);
    }

    // Collect all credential keys with their dot-path for reporting.
    $findings = [];
    $this->scanYamlArray($info, $findings);

    if (!empty($findings)) {
      $tokens = $phpcsFile->getTokens();
      foreach ($findings as $finding) {
        $keyName = $finding['key'];
        $lineNum = $this->findYamlKeyLine($keyName, (string) $finding['value'], $tokens);
        if ($lineNum === NULL) {
          continue;
        }
        // Respect inline # phpcs:ignore annotations in YAML files.
        // Native PHPCS suppression does not apply to T_INLINE_HTML tokens.
        $lineContent = $tokens[$lineNum]['content'] ?? '';
        if ($this->hasPhpcsIgnoreAnnotation($lineContent)) {
          continue;
        }
        $error = sprintf(
          "Hardcoded credential '%s' detected. Use environment variables or the Drupal Key module to manage secrets. @see https://www.drupal.org/project/key",
          $keyName
        );
        $phpcsFile->addError($error, $lineNum, 'HardcodedCredential');
      }
    }

    return ($phpcsFile->numTokens + 1);
  }

  /**
   * Recursively scan a parsed YAML array for credential keys with hardcoded values.
   *
   * @param array $data
   *   The parsed YAML data.
   * @param array &$findings
   *   Array to collect findings.
   */
  protected function scanYamlArray(array $data, array &$findings) {
    foreach ($data as $key => $value) {
      if (is_array($value)) {
        $this->scanYamlArray($value, $findings);
        continue;
      }

      if (!is_string($key)) {
        continue;
      }

      if (preg_match($this->credentialPattern, $key) && $this->isHardcodedValue($value)) {
        $findings[] = ['key' => $key, 'value' => $value];
      }
    }
  }

  /**
   * Find the line number of a YAML key in the token stream.
   *
   * @param string $keyName
   *   The YAML key name to search for.
   * @param string $value
   *   The expected key value used to disambiguate duplicates.
   * @param array $tokens
   *   The token stream.
   *
   * @return int|null
   *   The token index where the key is found, or NULL when not found.
   */
  protected function findYamlKeyLine(string $keyName, string $value, array $tokens): ?int {
    $firstMatch = NULL;
    foreach ($tokens as $index => $token) {
      // YAML keys appear as "key:" or "key: value" in inline HTML tokens.
      $trimmed = ltrim($token['content']);
      if (strpos($trimmed, $keyName . ':') !== 0) {
        continue;
      }
      // Record first match as fallback.
      if ($firstMatch === NULL) {
        $firstMatch = $index;
      }
      // When the same key name appears in multiple places, prefer the line
      // that also contains the specific value — this disambiguates duplicates.
      if ($value !== '' && strpos($token['content'], $value) !== FALSE) {
        return $index;
      }
    }

    return $firstMatch;
  }

  /**
   * Process PHP variable assignments for hardcoded credentials.
   *
   * Detects patterns like: $password = 'hardcoded_value';
   *
   * @param \PHP_CodeSniffer\Files\File $phpcsFile
   *   The current file being processed.
   * @param int $stackPtr
   *   The position of the T_VARIABLE token.
   */
  protected function processPhpVariable(File $phpcsFile, $stackPtr) {
    $tokens = $phpcsFile->getTokens();
    $varName = $tokens[$stackPtr]['content'];

    // Strip the $ prefix.
    $cleanName = ltrim($varName, '$');

    if (!preg_match($this->credentialPattern, $cleanName)) {
      return;
    }

    // Look for assignment: $password = 'value';.
    $nextNonEmpty = $phpcsFile->findNext(Tokens::$emptyTokens, ($stackPtr + 1), NULL, TRUE, NULL, TRUE);
    if ($nextNonEmpty === FALSE || $tokens[$nextNonEmpty]['code'] !== T_EQUAL) {
      return;
    }

    // Find the value token after the equals sign.
    $valuePtr = $phpcsFile->findNext(Tokens::$emptyTokens, ($nextNonEmpty + 1), NULL, TRUE, NULL, TRUE);
    if ($valuePtr === FALSE) {
      return;
    }

    if ($tokens[$valuePtr]['code'] !== T_CONSTANT_ENCAPSED_STRING) {
      return;
    }

    $value = $this->stripQuotes($tokens[$valuePtr]['content']);
    if ($this->isHardcodedValue($value)) {
      $error = sprintf(
        "Hardcoded credential '%s' detected. Use environment variables or the Drupal Key module to manage secrets. @see https://www.drupal.org/project/key",
        $cleanName
      );
      $phpcsFile->addError($error, $stackPtr, 'HardcodedCredential');
    }
  }

  /**
   * Process PHP array key => value pairs for hardcoded credentials.
   *
   * Detects patterns like: 'api_key' => 'hardcoded_value'
   *
   * @param \PHP_CodeSniffer\Files\File $phpcsFile
   *   The current file being processed.
   * @param int $stackPtr
   *   The position of the T_CONSTANT_ENCAPSED_STRING token.
   */
  protected function processPhpArrayKey(File $phpcsFile, $stackPtr) {
    $tokens = $phpcsFile->getTokens();
    $keyContent = $this->stripQuotes($tokens[$stackPtr]['content']);

    if (!preg_match($this->credentialPattern, $keyContent)) {
      return;
    }

    // Look for => after the key.
    $nextNonEmpty = $phpcsFile->findNext(Tokens::$emptyTokens, ($stackPtr + 1), NULL, TRUE, NULL, TRUE);
    if ($nextNonEmpty === FALSE || $tokens[$nextNonEmpty]['code'] !== T_DOUBLE_ARROW) {
      return;
    }

    // Find the value token after =>.
    $valuePtr = $phpcsFile->findNext(Tokens::$emptyTokens, ($nextNonEmpty + 1), NULL, TRUE, NULL, TRUE);
    if ($valuePtr === FALSE) {
      return;
    }

    if ($tokens[$valuePtr]['code'] !== T_CONSTANT_ENCAPSED_STRING) {
      return;
    }

    $value = $this->stripQuotes($tokens[$valuePtr]['content']);
    if ($this->isHardcodedValue($value)) {
      $error = sprintf(
        "Hardcoded credential '%s' detected. Use environment variables or the Drupal Key module to manage secrets. @see https://www.drupal.org/project/key",
        $keyContent
      );
      $phpcsFile->addError($error, $stackPtr, 'HardcodedCredential');
    }
  }

  /**
   * Determine if a value looks like a hardcoded credential.
   *
   * @param mixed $value
   *   The value to check.
   *
   * @return bool
   *   TRUE if the value appears to be a hardcoded credential.
   */
  protected function isHardcodedValue($value) {
    // Only flag string values.
    if (!is_string($value)) {
      return FALSE;
    }

    $trimmed = trim($value);

    // Skip empty strings.
    if ($trimmed === '') {
      return FALSE;
    }

    // Skip known placeholder values.
    if (in_array(strtolower($trimmed), $this->placeholders, TRUE)) {
      return FALSE;
    }

    // Skip environment variable references (Symfony/Drupal patterns).
    // e.g. %env(DATABASE_PASSWORD)%, ${ENV_VAR}, getenv('...')
    if (preg_match('/^%env\(.+\)%$/', $trimmed)) {
      return FALSE;
    }
    if (preg_match('/^\$\{.+\}$/', $trimmed)) {
      return FALSE;
    }

    return TRUE;
  }

  /**
   * Check whether a line contains a phpcs:ignore annotation for this sniff.
   *
   * Handles both generic suppression (phpcs:ignore) and sniff-specific
   * suppression (phpcs:ignore DrupalSecurity.Credentials.HardcodedCredentials).
   *
   * @param string $lineContent
   *   The raw content of the line.
   *
   * @return bool
   *   TRUE if the line should be suppressed.
   */
  protected function hasPhpcsIgnoreAnnotation(string $lineContent): bool {
    if (strpos($lineContent, 'phpcs:ignore') === FALSE) {
      return FALSE;
    }
    // If a dot-separated sniff code is specified, only suppress when it
    // references this sniff.  The pattern deliberately excludes tokens like
    // "--" so that "phpcs:ignore -- reason" is treated as a bare suppression.
    if (preg_match('/phpcs:ignore\s+([A-Za-z][\w.]+)/', $lineContent, $matches)) {
      $specified = $matches[1];
      return strpos($specified, 'DrupalSecurity.Credentials.HardcodedCredentials') === 0;
    }
    // Bare phpcs:ignore (with no sniff code) suppresses everything on the line.
    return TRUE;
  }

  /**
   * Strip surrounding quotes from a string.
   *
   * @param string $str
   *   The quoted string.
   *
   * @return string
   *   The string without surrounding quotes.
   */
  protected function stripQuotes($str) {
    if (strlen($str) >= 2) {
      $first = $str[0];
      $last = $str[strlen($str) - 1];
      if (($first === '"' && $last === '"') || ($first === "'" && $last === "'")) {
        return substr($str, 1, -1);
      }
    }

    return $str;
  }

}
